#!/usr/bin/env bash

#This command will run the ansible container as it was the ansible command.
# Is maps all the user id_rsa and is_rsa.pub 

docker run --rm -it \
  -v ~/.ssh/id_rsa:/root/.ssh/id_rsa \
  -v ~/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub \
  -v $(pwd):/ansible_playbooks \
  -v /var/log/ansible/ansible.log \
ansible-playbook "$@"
